- .github/workflows/check_config_docs.yaml
- .github/workflows/check_openapi_specs.yaml
- .github/workflows/check_pyproject.yaml
- .github/workflows/check_readmes.yaml
- .github/workflows/get_affected_services.yaml
- .github/workflows/static_code_analysis.yaml
- .github/workflows/tests_on_pr.yaml
- .github/workflows/tests_on_push.yaml
- .pyproject_generation/pyproject_template.toml
- pyproject.toml
- scripts/update_readme_services.py
This contains all common workflows without caching.
Testing and static code analysis fail currently and need some work on the service level, so I'd do the fixing on a separate branch based on these changes.
I also left the other branch with the caching experiments open for future reference (https://github.com/ghga-de/file-services-backend/tree/add_needed_workflows)
> Non optimized workflows

- .pre-commit-config.yaml
- services/ifrs/tests_ifrs/conftest.py
- services/ifrs/tests_ifrs/fixtures/joint.py
- services/ifrs/tests_ifrs/test_ifrs_edge_cases.py
- services/ifrs/tests_ifrs/test_ifrs_typical_journey.py
- services/irs/tests_irs/conftest.py
- services/irs/tests_irs/fixtures/joint.py
- services/irs/tests_irs/test_cli.py
- services/irs/tests_irs/test_event_handling.py
Remove the use of the second_s3 fixture from tests. The tests had a flaw with resetting state and the current hexkit fixture setup doesn't allow for multiple containers (this might need to be adapted in the future). The intention with the affected tests in this PR was originally to test potential side effects when multiple storage nodes exist. This could/should be tested with integration tests later, but that still might require the ability to instantiate more than one s3 container. 
The changes to both IRS and IFRS tests are basically:
- Remove second_s3 fixture
- Remove `for` loop in tests iterating through s3/second_s3 fixtures, then unindent everything that was under it (responsible for big change block)
- Only use node1 storage location (did not check super closely for this)
- Move …
> Adapt test fixtures

- services/ucs/README.md
- services/ucs/config_schema.json
- services/ucs/dev_config.yaml
- services/ucs/example_config.yaml
- services/ucs/openapi.yaml
- services/ucs/pyproject.toml
- services/ucs/src/ucs/adapters/inbound/event_sub.py
- services/ucs/src/ucs/config.py
- services/ucs/src/ucs/core/models.py
- services/ucs/src/ucs/core/upload_service.py
- services/ucs/src/ucs/inject.py
- services/ucs/src/ucs/main.py
- services/ucs/tests_ucs/fixtures/config.py
- services/ucs/tests_ucs/fixtures/joint.py
- services/ucs/tests_ucs/fixtures/test_config.yaml
- services/ucs/tests_ucs/test_edge_cases.py
- services/ucs/tests_ucs/test_typical_journey.py
Adds an outbox subscriber/translator with minimal changes otherwise. Idempotence is built in to the core, so no IdempotenceHandler is needed.
Previously, the UCS would publish a `FileDeletionSuccessful` event anytime it consumed a `FileDeletionRequested` event, even if nothing was there to be deleted (e.g. in the case of an re-processing or something). This has been changed so an event is only published if an upload attempt is discovered. I didn't know whether to base it on the object deletion or the upload attempts and went with the broader thing, but this can easily be changed.
> UCS Outbox Subscriber (GSI-774)

- services/irs/README.md
- services/irs/config_schema.json
- services/irs/dev_config.yaml
- services/irs/example_config.yaml
- services/irs/pyproject.toml
- services/irs/src/irs/adapters/inbound/event_sub.py
- services/irs/src/irs/adapters/outbound/dao.py
- services/irs/src/irs/config.py
- services/irs/src/irs/inject.py
- services/irs/src/irs/main.py
- services/irs/tests_irs/conftest.py
- services/irs/tests_irs/fixtures/joint.py
- services/irs/tests_irs/fixtures/test_config.yaml
- services/irs/tests_irs/test_cli.py
- services/irs/tests_irs/test_event_handling.py
- services/irs/tests_irs/test_outbox_subscriber.py
Adds an outbox subscriber to handle the FileUploadReceived events. There is no extra idempotence mechanism added in this PR because that is already handled by the Interrogator class via the Fingerprint process. The `changed` method on the outbox translator class has the same action as the event sub translator when consuming the event, and calls the `interrogate` method on the interrogator. 
The `deleted` method will log a warning, as is done in similar implementations for outbox consumption of normal events.
Because there is a config change, the major version number is bumped from 2 -> 3
> IRS Outbox Subscriber (GSI-779)

- services/fis/src/fis/cli.py
- services/fis/src/fis/main.py
- services/fis/tests_fis/fixtures/joint.py
- services/fis/tests_fis/test_outbox_dao.py
Exposes the republish functionality with the cli command `publish-events`. By default, this will publish only pending documents. Adding the `--all` flag with republish all events, regardless of publish status.
> FIS Add Republish Command (GSI-814)

- services/fis/src/fis/cli.py
- services/fis/tests_fis/test_outbox_dao.py
- services/pcs/src/pcs/cli.py
When `all` is annotated with `typer.Argument`, it doesn't work like a flag very well. Using `typer.Option` gives it the intuitive behavior, i.e. `fis publish-events` or `fis publish-events --all`. Using typer.Argument and `--all` results in an error.
> pcs and fis: Fix publish-events command

- .github/workflows/ci_docker.yaml
- .github/workflows/get_affected_services.yaml
This PR changes the behaviour of the docker-ci workflow and adds new input variables to the get-affected-services workflow.
A distinction betwee fetch-depths has been made between the checkout and compare action, as the documentation for the latter one was lacking in respect to its behaviour when passing 0, so an explicit value is passed instead.
Two cases need to be distinguished on release: 
We already have a previous tag or we don't.
For the first case, comparison is made based on the commit corresponding to the tag representing the previous release.
If no tag exists, the first commit to the repo is used as comparison base instead and needs a sufficiently large fetch depth, so this one is also explicitly set.
I could not verify if the actual publish job works locally, so we will have …
> Docker publish now only runs on release

- .github/workflows/docker_on_release.yaml
Found an easy solution to check if a docker image already exists:
Just pull the image, and if successful, fail the step by exiting with a non-zero code.
If pulling fails, just do nothing.
Needs an `or` in after the pull command, else it fails on an unsuccessful pull.
This also renames the action and removes the suffix sha from the docker tag.
> Docker workflow improvements

- .pyproject_generation/pyproject_custom.toml
- pyproject.toml
- services/ekss/README.md
- services/ekss/config_schema.json
- services/ekss/example_config.yaml
- services/ekss/openapi.yaml
- services/ekss/pyproject.toml
- services/ekss/src/ekss/adapters/outbound/vault/client.py
- services/ekss/src/ekss/config.py
- services/fis/README.md
- services/fis/config_schema.json
- services/fis/example_config.yaml
- services/fis/openapi.yaml
- services/fis/pyproject.toml
- services/fis/src/fis/adapters/outbound/vault/client.py
Exposes kubernetes adapter mount point as config option called `vault_kube_mount_point` analogously to the already existing `vault_kube_role`.
> Added auth mount point to vault adapter

- .github/workflows/check_config_docs.yaml
- .github/workflows/check_openapi_specs.yaml
- .github/workflows/check_readmes.yaml
- .github/workflows/ci_workflow_dispatch.yaml
- .github/workflows/docker_on_release.yaml
- .github/workflows/tests.yaml
If condition dealt with the totally broken case so far, but did not catch the legitimate empty array when no services were affected.
> Check for empty array in workflow strategy input

- services/fis/README.md
- services/fis/openapi.yaml
- services/fis/pyproject.toml
- services/fis/src/fis/adapters/inbound/fastapi_/configure.py
- services/fis/src/fis/adapters/inbound/fastapi_/routes.py
- services/fis/src/fis/adapters/outbound/vault/client.py
- services/fis/src/fis/core/ingest.py
- services/fis/src/fis/core/models.py
- services/fis/src/fis/ports/inbound/ingest.py
- services/fis/src/fis/ports/outbound/vault/client.py
- services/fis/tests_fis/test_api_call.py
- services/fis/tests_fis/test_ingest.py
This PR adds two simple lookups to the File Ingest Service, one for each ingest endpoint to abort any further processing if the file ID has already been processed.
As the entry in the outbox DAO is only created once everything else is done, we can reasonably assume that the presence of a corresponding entry means the ingest of a specific file has succeeded previously - at least inside the FIS.
This will still produce additional new secret entries in vault for the legacy path if something should crash before an entry is created, but the information is only propagated once in this case.
Also, decided to return to 202 for the no-op as well, as we don't need to distinguish between the new and already seen case on the client side and this would require a small change to the DS-Kit if we go …
> Idempotency guards

- .github/workflows/push_to_docker/action.yaml
There are these discussions about the issue: https://github.com/aquasecurity/trivy/discussions/7668 and https://github.com/aquasecurity/trivy-action/issues/389
There is a PR in progress for this still open https://github.com/aquasecurity/trivy-action/pull/433
People mention a workaround to specify alternative DB. https://github.com/aquasecurity/trivy/discussions/7668#discussioncomment-10879681 It seems like if you specify multiple DB repositories Trivy retries the next one if the primary repository fails. There are three repositories for Trivy DB and they are updated every 6 hours together.
> Fix trivy in GitHub action

- services/ifrs/README.md
- services/ifrs/pyproject.toml
- services/ifrs/src/ifrs/core/file_registry.py
- services/ifrs/src/ifrs/ports/inbound/file_registry.py
- services/ifrs/tests_ifrs/test_ifrs_edge_cases.py
Bumps ifrs version to 2.1.2
The S3 provider in hexkit already checks to make sure the object doesn't exist in the destination bucket, so I removed the same check from the IFRS -- instead, it will catch the corresponding error, log, and return (same behavior as before).
The potential other errors, listed below, are all logged and re-raised:
- The object metadata is missing important info like ContentLength
- The object is over 5 TiB
- Miscellaneous errors in the boto3 copy/multipart upload operation itself
> IFRS - Improve file staging error handling (GSI-1190)

- services/dcs/README.md
- services/dcs/config_schema.json
- services/dcs/example_config.yaml
- services/dcs/openapi.yaml
- services/dcs/pyproject.toml
- services/dcs/src/dcs/adapters/inbound/fastapi_/dummies.py
- services/dcs/src/dcs/adapters/inbound/fastapi_/routes.py
- services/dcs/src/dcs/core/data_repository.py
- services/dcs/src/dcs/inject.py
- services/dcs/src/dcs/ports/inbound/data_repository.py
- services/dcs/tests_dcs/fixtures/joint.py
- services/dcs/tests_dcs/test_edge_cases.py
- services/dcs/tests_dcs/test_typical_journey.py
Added `cache-control` header with `max-age` to the response for the main endpoint `GET /objects/{object_id}`. 
The value used for `max-age` is set to the config value `presigned_url_expires_after`.
The primary integration test was updated to check for the header.
> DCS: Response cache headers (GSI-1243)

- services/ekss/README.md
- services/ekss/openapi.yaml
- services/ekss/pyproject.toml
- services/ekss/src/ekss/adapters/inbound/fastapi_/exceptions.py
- services/ekss/src/ekss/adapters/inbound/fastapi_/router.py
- services/ekss/src/ekss/config.py
- services/ekss/tests_ekss/integration/test_post_endpoint.py
- services/ekss/tests_ekss/unit/test_config_validators.py
- Both the server public and private key are now decoded and the length is checked in a validator to catch issues early and crash on startup instead of on the first request.
- An additional Response, HttpDecodingError, is now produced by both endpoints receiving base64 encoded data. Failure to decode either the client/requester public key or the file part means something went wrong before the data hits the EKSS and accordingly should be handled by the caller instead of crashing the EKSS
> Server keypair validators and decoding error handling

- services/dcs/README.md
- services/dcs/openapi.yaml
- services/dcs/pyproject.toml
- services/dcs/src/dcs/adapters/inbound/event_sub.py
- services/dcs/src/dcs/core/data_repository.py
- services/dcs/src/dcs/core/models.py
- services/dcs/tests_dcs/fixtures/joint.py
- services/dcs/tests_dcs/test_edge_cases.py
Populate encrypted object size from incoming event instead of fetching it from S3 every time.
Skip existence lookup and move it into error handling branch, i.e. RetryLater response is now the error handling branch of getting the presigned URL.
Added some debug logging around service external calls measuring exection time.
> [major] DCS: Fetch (encrypted) object size from S3 incoming event

- services/ifrs/README.md
- services/ifrs/config_schema.json
- services/ifrs/dev_config.yaml
- services/ifrs/example_config.yaml
- services/ifrs/src/ifrs/__main__.py
- services/ifrs/src/ifrs/config.py
- services/ifrs/src/ifrs/migration_logic/__init__.py
- services/ifrs/src/ifrs/migration_logic/_manager.py
- services/ifrs/src/ifrs/migration_logic/_utils.py
- services/ifrs/src/ifrs/migration_logic/ifrs_migrations.py
- services/ifrs/src/ifrs/migrations.py
- services/ifrs/tests_ifrs/fixtures/test_config.yaml
- services/ifrs/tests_ifrs/test_migrations.py
Adds a very rough version of the migration framework which aims to minimize the amount of related code required to be maintained across services without being too restricting/prescriptive.
**Step 1**: The logic for every migration should subclass `MigrationDefinition` and, usually, `Reversible` as well:
```python
class V2Migration(MigrationDefinition, Reversible):
"""Adds `object_size` and migrates the database to version 2"""
version = 2
async def apply(self):
async with self.auto_finalize("file_metadata"):
await self.migrate_docs_in_collection(
coll_name=METADATA_COLLECTION,
change_function=my_change_function,
validation_model=FileMetadata,
id_field="file_id",
)
async def unapply(self):
...
```
**Step 2**: Define the current database version and the migration map. 
>In this prototype, …
> IFRS: prototype migration framework and object_size migration (GSI-1271)

- services/dcs/README.md
- services/dcs/config_schema.json
- services/dcs/dev_config.yaml
- services/dcs/example_config.yaml
- services/dcs/openapi.yaml
- services/dcs/src/dcs/config.py
- services/dcs/src/dcs/main.py
- services/dcs/src/dcs/migration_logic/__init__.py
- services/dcs/src/dcs/migration_logic/_manager.py
- services/dcs/src/dcs/migration_logic/_utils.py
- services/dcs/src/dcs/migration_logic/dcs_migrations.py
- services/dcs/src/dcs/migrations.py
- services/dcs/tests_dcs/fixtures/test_config.yaml
- services/dcs/tests_dcs/test_migrations.py
Copies over the same temporary migration framework from the IFRS. Migration manually calculates the encrypted object size using the [calculation found in the DS Kit ](https://github.com/ghga-de/ghga-datasteward-kit/blob/3da0419129393b48f116a086ad8c0a94815d7f7f/src/ghga_datasteward_kit/s3_upload/utils.py#L198). I did some preliminary verification of this approach beforehand by looking at what's in staging.
This will be part of the DCS v4 release
> Add encrypted_size migration to DCS (GSI-1290)

- services/dcs/README.md
- services/dcs/openapi.yaml
- services/dcs/pyproject.toml
- services/dcs/src/dcs/migration_logic/_utils.py
- services/dcs/tests_dcs/test_migrations.py
- services/ifrs/README.md
- services/ifrs/pyproject.toml
- services/ifrs/src/ifrs/migration_logic/_utils.py
- services/ifrs/tests_ifrs/test_migrations.py
Fixes an issue in the DCS/IFRS migration tools where we could potentially encounter errors during staging if a `tmp_vN_old_collname` exists, or during unstaging if `tmp_vN_new_collname` exists. These are unlikely to occur in production, but might be encountered in staging or local testing if the DB state is not properly managed.
Additionally, this PR fixes a problem in the `unstage` method where the collection `tmp_vN_old_collname` would be renamed to itself instead of `collname`, resulting in a MongoDB error.
Both IFRS and DCS version patch numbers have been bumped.
> [patch] Migration staging/unstaging fix (GSI-1329)

- .github/workflows/get_affected_services.yaml
Switching to [this version](https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised#use-the-stepsecurity-maintained-changed-files-action) to replace the security risk recently found in `tj-actions/changed-files`
> Use stepsecurity's drop-in replacement for the compromised action

- services/dcs/README.md
- services/dcs/config_schema.json
- services/dcs/dev_config.yaml
- services/dcs/example_config.yaml
- services/dcs/openapi.yaml
- services/dcs/pyproject.toml
- services/dcs/src/dcs/adapters/inbound/event_sub.py
- services/dcs/src/dcs/adapters/outbound/event_pub.py
- services/dcs/src/dcs/config.py
- services/dcs/src/dcs/core/data_repository.py
- services/dcs/src/dcs/core/models.py
- services/dcs/src/dcs/inject.py
- services/dcs/src/dcs/main.py
- services/dcs/src/dcs/migrations/__init__.py
- services/dcs/src/dcs/migrations/definitions.py
- services/dcs/src/dcs/migrations/entry.py
- services/dcs/src/dcs/ports/inbound/data_repository.py
- services/dcs/tests_dcs/fixtures/joint.py
- services/dcs/tests_dcs/fixtures/test_config.yaml
- services/dcs/tests_dcs/test_dlq.py
- services/dcs/tests_dcs/test_edge_cases.py
- services/dcs/tests_dcs/test_migrations.py
- services/dcs/tests_dcs/test_typical_journey.py
Ignore the failed mypy check because it's only flagging errors in other services. This will occur for all the PRs until they are merged into one.
- V2 migration that covers two collections: `drs_objects` and `dcsPersistedEvents`.
- Models updated to use UUID4 and UTCDatetime where appropriate
- Use of `now_as_utc` replaced with less precise `now_utc_ms_prec`
- `MongoDbDaoFactory` is now used as a context manager
> DCS Hexkit v6 + Migrations (GSI-1780)

- services/irs/README.md
- services/irs/config_schema.json
- services/irs/pyproject.toml
- services/irs/src/irs/adapters/inbound/event_sub.py
- services/irs/src/irs/adapters/outbound/event_pub.py
- services/irs/src/irs/core/interrogator.py
- services/irs/src/irs/core/models.py
- services/irs/src/irs/core/storage_inspector.py
- services/irs/src/irs/inject.py
- services/irs/tests_irs/fixtures/files_for_testing.py
- services/irs/tests_irs/test_cli.py
- services/irs/tests_irs/test_dlq.py
- services/irs/tests_irs/test_event_handling.py
- services/irs/tests_irs/test_republish.py
Bump irs to version 7 and use hexkit v6.
I left the IRS-specific definitions of `object_id` here as strings because of the blind way the IRS queries S3 for stale objects, some annoying test inconsistencies that would result, and because it really just doesn't need to change right now (not deployed). There's also no migration.
> IRS: Hexkit v6 (GSI-1788)

- services/fis/README.md
- services/fis/config_schema.json
- services/fis/example_config.yaml
- services/fis/openapi.yaml
- services/fis/pyproject.toml
- services/fis/src/fis/adapters/outbound/event_pub.py
- services/fis/src/fis/core/ingest.py
- services/fis/src/fis/core/models.py
- services/fis/src/fis/inject.py
- services/fis/src/fis/main.py
- services/fis/src/fis/migrations/definitions.py
- services/fis/src/fis/migrations/entry.py
- services/fis/tests_fis/fixtures/joint.py
- services/fis/tests_fis/test_api_call.py
- services/fis/tests_fis/test_ingest.py
- services/fis/tests_fis/test_migrations.py
Ignore the failed mypy check because it's only flagging errors in other services. This will occur for all the PRs until they are merged into one.
- V3 migration that covers just the `fisPersistedEvents` collection
- Models updated to use UUID4 and UTCDatetime where appropriate
- Use of `now_as_utc` replaced with less precise `now_utc_ms_prec`
- `MongoDbDaoFactory` is now used as a context manager
I left otel & `@start_span()` in there because it is still hexkit v6 
Went for a slightly different approach for the migration test than in the last few PRs. I created the original, migrated, and reverted expected outputs upfront and tried to directly equate the output.
> FIS - hexkit v6 + migration for persistent events

- services/pcs/README.md
- services/pcs/config_schema.json
- services/pcs/dev_config.yaml
- services/pcs/example_config.yaml
- services/pcs/openapi.yaml
- services/pcs/pyproject.toml
- services/pcs/src/pcs/config.py
- services/pcs/src/pcs/inject.py
- services/pcs/src/pcs/main.py
- services/pcs/src/pcs/migrations/__init__.py
- services/pcs/src/pcs/migrations/definitions.py
- services/pcs/src/pcs/migrations/entry.py
- services/pcs/tests_pcs/fixtures/test_config.yaml
- services/pcs/tests_pcs/test_migrations.py
Migrate the PCS's persistent event store for hexkit v6. The persistent events consist only of "FileDeletionRequested" events, so the payload field doesn't need to be checked. Thus, the migration is straightforward.
Bumps the PCS to version `7.0.0`.
> PCS - use hexkit v6 (GSI-1787)

- services/ifrs/README.md
- services/ifrs/config_schema.json
- services/ifrs/dev_config.yaml
- services/ifrs/example_config.yaml
- services/ifrs/pyproject.toml
- services/ifrs/src/ifrs/adapters/inbound/event_sub.py
- services/ifrs/src/ifrs/adapters/outbound/event_pub.py
- services/ifrs/src/ifrs/config.py
- services/ifrs/src/ifrs/core/file_registry.py
- services/ifrs/src/ifrs/core/models.py
- services/ifrs/src/ifrs/inject.py
- services/ifrs/src/ifrs/main.py
- services/ifrs/src/ifrs/migrations/__init__.py
- services/ifrs/src/ifrs/migrations/definitions.py
- services/ifrs/src/ifrs/migrations/entry.py
- services/ifrs/src/ifrs/ports/inbound/file_registry.py
- services/ifrs/src/ifrs/ports/outbound/event_pub.py
- services/ifrs/tests_ifrs/fixtures/example_data.py
- services/ifrs/tests_ifrs/fixtures/joint.py
- services/ifrs/tests_ifrs/fixtures/test_config.yaml
- services/ifrs/tests_ifrs/test_ifrs_edge_cases.py
- services/ifrs/tests_ifrs/test_ifrs_typical_journey.py
- services/ifrs/tests_ifrs/test_migrations.py
Moves IFRS to version `6.0.0`.
Adds IFRS v2 migration to update the `file_metadata` and `ifrsPersistedEvents` collections.
Updates core module error logging to include traceback.
Uses `MongoDbDaoFactory` context manager.
> IFRS - hexkit v6 (GSI-1785)
